# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{switches}
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Seamus Abshere"]
  s.date = %q{2009-11-02}
  s.description = %q{
Switches lets you turn on and off parts of your code from the commandline. There's a defaults.yml and a current.yml in the background.

For example:
app/models/user.rb
after_create :subscribe_email if Switches.campaign_monitor?

>> Switches.campaign_monitor?
# => false

$ rake switches:on[campaign_monitor]

>> Switches.campaign_monitor?
# => true

$ rake switches:reset # goes back to default.yml
$ rake switches:diff  # shows diff b/w current.yml and default.yml
$ rake s:d            # alias for switches:diff
$ rake s:c            # alias for switches:list_current

etc.

It's inspired by ActiveSupport's StringInquirer (e.g. Rails.development?) and traditional compile-time assertions.
    }
  s.email = %q{seamus@abshere.net}
  s.extra_rdoc_files = [
    "LICENSE",
     "README",
     "README.html",
     "README.markdown"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "lib/switches.rb",
     "lib/tasks/capistrano_tasks.rb",
     "lib/tasks/switches.rake",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/switches_spec.rb",
     "switches.gemspec"
  ]
  s.homepage = %q{http://github.com/seamusabshere/switches}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{switches}
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Turn on and off parts of your code based on yaml files.}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/switches_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<activesupport>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<activesupport>, [">= 0"])
  end
end

